import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import HeaderHome from "@/app/components/header";
import FooterHome from "@/app/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="h-screen bg-gradient-to-br from-gray-950 via-orange-950 to-gray-950 flex flex-col">
          <HeaderHome/>
          <div className="flex-1 flex flex-col items-center justify-evenly">
              {children}
          </div>
          <FooterHome/>
      </div>
      </body>
    </html>
  );
}
