import type { Metadata } from "next";
import "@/ui/styles/globals.css";
import DarkModeInit from "@/app/root-components/dark-mode-init";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="h-screen w-screen">
            <DarkModeInit />
            {children}
        </body>
        </html>
    );
}
